### ISSUE TITLE
Integration of observability into discovery engine

### ISSUE THREAD

**Issue by seswarrajan** [accuknox/discovery-engine#472]
This issue/task is created for integration of observability as part of discovery-engine.
 
### Task List
- [x] Create observability DB for network and system
- [x] Reuse observability protobuf
- [x] Create a config if required for observability
- [x] Create Insert/Update/Delete APIs for observability DB
- [x] Use observability's summary logic and port it to discovery engine(since values in observability is hardcoded, cannot use the same API)
